#!/usr/bin/python

# Include all the common functions and libraries.
from cloudperm import *

# Add on any specific arguments that this program requires.
try:
    import argparse
    parser = argparse.ArgumentParser(parents=[cloudperm_argparser])
    parser.add_argument('documents', metavar='DocumentID', type=str, nargs='+', help='Google Document IDs')
    args = parser.parse_args()
except ImportError:
    args = None



def main():
    """
    Connect to Google Drive and get the list of permissions for the DocumentIDs provided.
    """

    pp = pprint.PrettyPrinter(indent=4)

    credentials = get_credentials(args)
    http = credentials.authorize(httplib2.Http())
    service = discovery.build('drive', 'v2', http=http)
	
    parser = SafeConfigParser()
    parser.read("DriveConfig.INI")

    # Get our list of file IDs to check, either form the config file or from the command line arguments.

    fileids = [];

    if args.documents:
        for fileid in args.documents:
            fileids.append(fileid)
        
    else:
        for section in parser.sections(): # Fix this later.
            for name,value in parser.items(section):
                if name == "url":
                    fileids.append(value)

    for fileid in fileids:
        title = retrieve_document_title(service, fileid);
        print("Document Title: " + str(title));
        perm_list = retrieve_permissions(service, fileid)
        parents = retrieve_document_parents(service, fileid)
        #print("Parents: " + str(parents))
        for entry in perm_list:
            if type(entry) is dict:
                if 'emailAddress' in entry:
                    print("  " + entry['role'] + ":  " + entry['emailAddress']);
                else: # This probably is an entry that implies anyone with link or public.
                    #print("Entry json: " + str(entry));
                    if (entry['type'] == 'anyone' and entry['id'] == 'anyoneWithLink'):
                        print("  WARNING: ANYONE WITH THE LINK CAN READ THIS DOCUMENT.");
                    elif (entry['type'] == 'anyone' and entry['id'] == 'anyone'):
                        print("  WARNING: THIS DOCUMENT IS PUBLIC AND CAN BE FOUND AND READ BY ANYONE WITH A SEARCH.");
                    elif (entry['type'] == 'domain'):
                        permitted_domain = entry['domain'];
                        domain_allowed_role = entry['role'];
                        print("  WARNING: ANYONE FROM THE DOMAIN '" + permitted_domain + "' HAS '" + domain_allowed_role + "' PERMISSION TO THIS DOCUMENT.");
                    else:
                        # Handle the unknown case in a helpful way.
                        print(" Unknown permission type:");
                        pp = pprint.PrettyPrinter(indent=8,depth=6)
                        pp.pprint(entry);

                    	

if __name__ == '__main__':
    main()


