#!/usr/bin/env python3
# Include all the common functions and libraries.
from cloudperm import *

import configparser
import csv
import json

import sqlite3
from sqlite3 import Error

# Add on any specific arguments that this program requires.
try:
    import argparse
    parser = argparse.ArgumentParser(parents=[cloudperm_argparser])
    parser.add_argument('documents', metavar='DocumentID', type=str, nargs='+', help='Google Document IDs')
    args = parser.parse_args()
except ImportError:
    args = None


makeDB() 
def main():
    """
    Connect to Google Drive and get the list of permissions for the DocumentIDs provided.
    """

    pp = pprint.PrettyPrinter(indent=4)

    credentials = get_credentials(args)
    http = credentials.authorize(httplib2.Http())
    service = discovery.build('drive', 'v2', http=http)
	
    parser = configparser.ConfigParser()
    parser.read("DriveConfig.INI")

    # Get our list of file IDs to check, either form the config file or from the command line arguments.

    fileids = [];

    if args.documents:
        for fileid in args.documents:
            fileids.append(fileid)
        
    else:
        for section in parser.sections(): # Fix this later.
            for name,value in parser.items(section):
                if name == "url":
                    fileids.append(value)
    #####################################################################

    permission(fileids, service)

if __name__ == '__main__':
    drop()
    main()


